//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEstudiantes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASES
    {
        public CLASES()
        {
            this.ESTUDIANTES = new HashSet<ESTUDIANTES>();
        }
    
        public int ID_CLASE { get; set; }
        public int ID_MATERIA { get; set; }
        public string NOMBRE { get; set; }
        public string HORARIO { get; set; }
    
        public virtual MATERIAS MATERIAS { get; set; }
        public virtual ICollection<ESTUDIANTES> ESTUDIANTES { get; set; }
    }
}
