//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEstudiantes.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ESTUDIANTES
    {
        [Display(Name ="#")]
        public int ID_ESTUDIANTE { get; set; }
        [Display(Name = "Clase Inscrita")]
        public int ID_CLASE { get; set; }
        [Display(Name = "Nombre del Estudiante")]
        public string NOMBRE { get; set; }
    
        public virtual CLASES CLASES { get; set; }
    }
}
