CREATE DATABASE GESTION_ESTUDIANTES;

CREATE TABLE dbo.ESTUDIANTES (
    ID_ESTUDIANTE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(100),
    LineNumber SMALLINT NOT NULL,
    ProductID INT NULL,
    UnitPrice MONEY NULL,
    OrderQty SMALLINT NULL,
    ReceivedQty FLOAT NULL,
    RejectedQty FLOAT NULL,
    DueDate DATETIME NULL
);
ALTER TABLE dbo.CLASES   
DROP CONSTRAINT FK_CLASE_MATERIA;  
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MATERIAS]') AND type in (N'U'))
DROP TABLE [dbo].[MATERIAS]
GO
CREATE TABLE dbo.MATERIAS (
    ID_MATERIA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,	
	NOMBRE VARCHAR(100),
    CREDITOS INT NULL,    
);

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLASES]') AND type in (N'U'))
DROP TABLE [dbo].[CLASES]
GO
CREATE TABLE dbo.CLASES (
    ID_CLASES INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ID_MATERIA INT NOT NULL ,
	NOMBRE VARCHAR(100),
	HORARIO VARCHAR(50),
    CONSTRAINT FK_CLASE_MATERIA FOREIGN KEY (ID_MATERIA) REFERENCES MATERIAS (ID_MATERIA), 
);

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROFESORES]') AND type in (N'U'))
DROP TABLE [dbo].[PROFESORES]
GO
CREATE TABLE dbo.PROFESORES (
    ID_PROFESOR INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ID_MATERIA INT NOT NULL ,
	NOMBRE VARCHAR(100),
    CONSTRAINT FK_PROFESOR_MATERIA FOREIGN KEY (ID_MATERIA) REFERENCES MATERIAS (ID_MATERIA), 
);